### ISSUE TITLE
Archetype with release profile 

### ISSUE THREAD

**Issue by nicoulaj** [techatspree/android-archetypes#1]
Hi,
After some cleaning I could contribute a release profile that can sign, zipalign and obfuscate code. Are you interested ?

**Comment by cescoffier** [comment]
Of course I'm ! 

Thanks !

**Comment by nicoulaj** [comment]
See Issue 2.

**Comment by cescoffier** [comment]
I've integrated your pull request. Thanks !
I'm just wondering about the name (android-full), but this is pretty minor.

**Comment by nicoulaj** [comment]
Yes, feel free to change it, I was not very inspired...

**Comment by cescoffier** [comment]
Hi,
I did a couple of changes...
- The archetypes is now called android-release
- The proguard configuration now use proguard 4.4
- I've slightly modified the maven-jarsigner-plugin (cosmetic changes, + execution of 'verify')
- I ensure that in release mode, IT runs against the zipaligned artifact
- I've attached the obfuscation mapping to the project
- the rt.jar path is system specific, I've added profiles to detect the correct one.

Feel free to review those changes. If everything is fine, I will cut a release this week. 

Thanks again for your work !

**Comment by nicoulaj** [comment]
Nice !
I will try it this week. I was planning to make some changes too:
- ProGuard seems to be quite dangerous and may cause issues at runtime (because of obfuscation changing fields and method names), for example if you use the LVL. I will try to complete proguard.conf, but I'm sure there is one one config that can work for all apps...
- proguard.conf can be completed to strip calls to Log.*(), which is a pretty easy way to turn off logging for release builds.
- rt.jar is not only the JDK jar to take into account, I had to add jsse.jar too for example.

**Comment by cescoffier** [comment]
To be honest, we're not using proguard here... so my experience is quite limited.

About rt.jar and jsse.jar it's already done.

We've tested it on Mac and Linux.

**Comment by nicoulaj** [comment]
Everything works fine for me too. I have pushed a few little things to my fork, if you want to pick them...

**Comment by cescoffier** [comment]
Makes sense,
will pull that ASAP.

My only concern is about removing log calls. It has a side effect. Log methods return an integer which is more or less the number of characters written in the log. This obviously may have an impact of the application behavior if the application expects to get this value. 

So, I will add a warning in the documentation about that.

**Comment by nicoulaj** [comment]
To be exact, ProGuard does not remove the call if the application uses the returned value. Log.*() methods are just marked as having no side effect, so ProGuard will remove simple calls to them.

But I agree with you the ProGuard processing in general can have unwanted effects, so maybe it would be better to just split it into another archetype, and mark it as experimental in the doc.

**Comment by cescoffier** [comment]
We can keep it for now, and add a documentation section about removing proguard. I think it's a nice feature for people interested by shrinking and obfuscating.

**Comment by cescoffier** [comment]
I've pulled your latest changes.
