### ISSUE TITLE
java.lang.NoSuchMethodError: android.test.ActivityInstrumentationTestCase2.<init>

### ISSUE THREAD

**Issue by samoKroslak** [techatspree/android-archetypes#10]
Hello, 

nice job with archetype, works ok in my environment - except tests 
when I choose to run tests, it always ends up with this error: 
http://sharetext.org/9DQ 
I'm using ant build file to call mvn clean install and then mvn android:package 
when I open test class "HelloAndroidActivity", everything seems to ok, no missing dependencies shown in IDE 

beware that I'm in the very beginning in android world so maybe I've missed something obvious, 
edit: ok, I had one mistake with version in test's .pom, however the resulting error is still the same 

Samo

**Comment by pose** [comment]
Hi, 

I think this is fixed with the following pull: https://github.com/akquinet/android-archetypes/pull/12

I should have posted the patch here directly, sorry for the mess.

Hope it helps,
Alberto

**Comment by samoKroslak** [comment]
yes, that fixed it for me, thanks! 

cheers, 
Samo
