### ISSUE TITLE
Proposal: donate project Maven Apache or Codehaus

### ISSUE THREAD

**Issue by rgladwell** [techatspree/android-archetypes#22]
This is probably a bit cheeky, but it would be nice if the android archetypes were automatically available in the M2E Archetype catalogue.

At the moment M2E users have to manually search for android archetype, entering details such as group and artefact IDs which is fiddly. It would be nice if the android archetypes were already registered with the archetype catalogues.

As I understand the only way to do this is if the archetypes have org.apache.\* or org.codehaus.\* artefact IDs. I also understand that to do this, you have to host your project with Apache or Codehaus.

**Comment by cescoffier** [comment]
Hi,

I'm not against, but I also do think that it should be done in collaboration (as a bundle) with the maven android plugin.

**Comment by rgladwell** [comment]
maven android plugin is definitely not contributing to the Apache or Codehaus unfortunately, they decided against it.

**Comment by cescoffier** [comment]
Then, I don't really see the point of moving. Just the archetype without the _main_ plugin, it will be a bit weird.

**Comment by rgladwell** [comment]
The advantage would be that the android archetype would be in the default archetype catalog, so users wouldn't have to manually enter the group ID, artefact ID and version to use it in M2E.

**Comment by cescoffier** [comment]
Hi,

I'm not an Eclipse user, but as far as I know it should be possible for the Eclipse plugin to add the archetype to the archetype list. No ?

**Comment by rgladwell** [comment]
They have to manually install it, see here for more information:

http://dev.eclipse.org/mhonarc/lists/m2e-dev/msg00806.html

**Comment by cescoffier** [comment]
What about using the _\* Archetype catalogs contributed via archetypeCatalogs extension point_ ?

**Comment by rgladwell** [comment]
This issue is redundant as we have now created a Android archetype catalog which is being successfully used in m2e-android to automatically offer android archetypes to users:

http://rgladwell.github.com/m2e-android/android-archetype-catalog.xml

You might want to host this yourselves.

**Comment by cescoffier** [comment]
What do you mean by _host this yourselves_. Do we have to add a catalog files somewhere on the web ?

**Comment by rgladwell** [comment]
There is a long-standing bug in m2e that means local archetype catalogs don't work. You don't have to host it, I'm hosting it at the moment on Github Pages, I just thought it might make more sense if you guys hosted it as part of the Android archetypes project.
