### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by peter-budo** [techatspree/android-archetypes#29]
Clement you previously mentioned new release. When do you think it will be available?

**Comment by cescoffier** [comment]
Probably this week. Will try to cut the release Today or tomorrow.

**Comment by peter-budo** [comment]
Can you please amend the android-maven-plugin version in README, I mentioned it in pull request, but it may escaped your attention

**Comment by cescoffier** [comment]
Fixed. I've also updated the changelog.
I probably will cut the release Today (integration tests in progress on our CI).

**Comment by peter-budo** [comment]
Thanx!

**Comment by cescoffier** [comment]
The archetypes were released and are now available from Maven Central.
