### ISSUE TITLE
Unable to create project from archetype

### ISSUE THREAD

**Issue by gengmzh** [techatspree/android-archetypes#31]
hi my issue is as follows

Unable to create project from archetype [de.akquinet.android.archetypes:android-quickstart:1.0.8]
org.apache.maven.archetype.exception.ArchetypeGenerationFailure: Error merging velocity templates: E:\xyzSpace\proj\ticket-office\pom.xml (设备未就绪。)

**Comment by cescoffier** [comment]
Hi,

Could you tell me how do you launch the generation (arguments ?)

**Comment by ebiermann** [comment]
If this is still a problem please create a new issue.
