### ISSUE TITLE
Maybe new archetype

### ISSUE THREAD

**Issue by peter-budo** [techatspree/android-archetypes#33]
Not sure if this is in general interest and if you willing to add this to the project, but maybe someone may find it useful.

I used my previous experiences with this project to create a specific archetype that we started to use in our company Novoda (https://github.com/novoda/android-archetypes).
Project is split into four modules:

<ul>
<li>app - android application (depends on core module)</li>
<li>core - "plain" Java, stuff that can be easier tested with JUnit and mocked with various frameworks (we try this section to be as much independent from Android, but sometimes some stuff sneak inside)</li>
<li>instrumentation - tests for Android stuff in app module</li>
<li>team - plain folder with team related stuff if one has to share some documents that may not necessary part of the project, coding standards etc</li>
</ul>

Few things to mention:

<ul>
<li>4.0.1.2 been made default Android version down to number of 4.0 devices and client requirements to build agains this version rather then 2.3 and/or lower</li>
<li>By default Android support library, action bar sherlock, robolectric, powermock been added</li>
<li>This setup also includes working setup for Emma reports with reports being build also on none rooted devices (Android Maven Plugin wiki info is rather difficult to follow get this setup going  http://code.google.com/p/maven-android-plugin/wiki/EmmaMaven)</li>
<li>.gitignore for IntelliJ and Eclipse</li>
</ul>

**Comment by cescoffier** [comment]
Except the team folder which may be a bit too tight to your organization, the rest could be a new archetype... We just need a name for it.

**Comment by peter-budo** [comment]
Sorry for delayed replay I was on holidays.

I can remove team folder.
However for name I was hopping to keep it as it is, given that project structure it is done in the "fashion" we use in Novoda  plus they allowed me to work on this.

**Comment by peter-budo** [comment]
Hmmm, since no comment was given I think outcome is clear. 
Is it OK with you if I spin novoda archetype as new project based on your project?

**Comment by cescoffier** [comment]
Hi,

The problem is that I'm no more in charge of the archetypes (I don't work for akquinet anymore). However,, I'm not against a fork on codehaus or apache. 

Clement

**Comment by peter-budo** [comment]
Hmm so who is in charge and can approve pull requests that I made for Jelly Bean addition?

**Comment by philippkumar** [comment]
Hi there,

I am.
The archetype without the team folder looks like a nice addition to the present archetypes. Alternatively, feel free to fork the project.

Best regards
Philipp

**Comment by peter-budo** [comment]
Will be forking project (only releasing novoda part) due to slow respond time on last pull request
