### ISSUE TITLE
m2e 1.1 now requires src/test/java folder

### ISSUE THREAD

**Issue by rgladwell** [techatspree/android-archetypes#34]
The new version of Maven for Eclipse (m2e 1.1) now requires all projects have a src/test/java folder and displays a build error marker if the folder does not exist. Could we add this folder to the Android archetypes to ensure users don't get build errors as soon as they start using the Android archetypes?

**Comment by diegoy** [comment]
It's happening to me too, I'm using Eclipse Juno and m2e 1.2.0

**Comment by rgladwell** [comment]
@diegoy Sorry this was an issue with m2e-android, please upgrade to the latest version

**Comment by kmav** [comment]
I am sorry I have the same issue and I use m2e 1.3.1... What software do I have to upgrade to the latest version? I used the instructions from http://rgladwell.github.io/m2e-android/ . I bypassed the issue by creating manually the folder src/test/java.

Thank you in advance...
