### ISSUE TITLE
Error using android-quickstart archetype in m2eclipse

### ISSUE THREAD

**Issue by rgladwell** [techatspree/android-archetypes#4]
To reproduce follow these steps:
1. Install m2eclipse plugin
2. In Eclipse select File -> New -> Project...
3. Select Maven -> Maven Project and click "Next"
4. Click "Next" again
5. Click "Add Archetype..."
6. In Archetype Group Id enter "de.akquinet.android.archetypes"
7. In Archetype Artifact Id" enter "android-quickstart"
8. In Archetype Version enter "1.0.4"
9. Click "OK"
10. Click Next
11. In "Group Id" enter "com.example" 
12. In "Artifact Id" enter "test-app"
13. Click Finish

Expected result: New Android project should be created in Eclipse

Actual result: get error message "Unable to create project from archetype [de.akquinet.android.archetypes:android-quickstart:1.0.4]". See attached Eclipse .log stacktrace

**Comment by rgladwell** [comment]
```
!ENTRY org.maven.ide.eclipse 4 -1 2011-02-04 21:11:39.700
!MESSAGE Unable to create project from archetype   [de.akquinet.android.archetypes:android-quickstart:1.0.4]
!STACK 0
org.apache.maven.archetype.exception.ArchetypeGenerationFailure: The defined artifact is not an archetype
at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:152)
at org.apache.maven.archetype.generator.DefaultArchetypeGenerator.generateArchetype(DefaultArchetypeGenerator.java:286)
at org.apache.maven.archetype.DefaultArchetype.generateProjectFromArchetype(DefaultArchetype.java:69)
at org.maven.ide.eclipse.internal.project.ProjectConfigurationManager.createArchetypeProject(ProjectConfigurationManager.java:459)
at org.maven.ide.eclipse.wizards.MavenProjectWizard$5.runInWorkspace(MavenProjectWizard.java:279)
at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by cescoffier** [comment]
Hi,

This is a bug in the archetype descriptors. I'm on it ! Thanks for reporting.

**Comment by rgladwell** [comment]
No worries, thanks for the great work on the archetypes. Hoping to add them to my GettingStarted page for m2eclipse-android-integration, or even integrating them inside the plugin.

Let me know if you need any help.

**Comment by cescoffier** [comment]
Hi,

I've just fixed the issue. Could you build the archetype from the current code and test?
Be sure you see the correct archetype in m2eclipse (1.5.0-SNAPSHOT). If it works, I will release it.

**Comment by rgladwell** [comment]
Which repo did you deploy the SNAPSHOT to? I think I need to add it to my settings.xml.

**Comment by cescoffier** [comment]
It's not deployed in any maven repo (I can deploy it on snapshots-central if you want).

You need to download the source and build the archetype (mvn clean install -DskipTests=true), and then rebuild your archetype catalog (mvn archetype:crawl).

**Comment by rgladwell** [comment]
Did you mean 1.0.5-SNAPSHOT? Test, seems to be working. Thanks!

**Comment by rgladwell** [comment]
Verified

**Comment by cescoffier** [comment]
Thanks !

**Comment by jasonsoso** [comment]
Unable to create project from archetype [de.akquinet.android.archetypes:android-quickstart:1.0.8 -> http://rgladwell.github.io/m2e-android]
The desired archetype does not exist (de.akquinet.android.archetypes:android-quickstart:1.0.8)
