### ISSUE TITLE
Remove proguard plugin

### ISSUE THREAD

**Issue by mosabua** [techatspree/android-archetypes#43]
The proguard run is now handled by the android maven plugin. The morseflash example app has the complete setup. The release archetype should be updated.

**Comment by rciovati** [comment]
Hello,
I started revamping these archetypes and I have updated the release archetype to match the morseflash example app.
A feedback from you would be really appreciated:

https://github.com/rciovati/android-archetypes/tree/revamped

**Comment by ebiermann** [comment]
Riccardo's change is part of version 1.0.10 of the archetype and Proguard is now handled by the android-maven-plugin.
