### ISSUE TITLE
New android archetype release?

### ISSUE THREAD

**Issue by jmdr** [techatspree/android-archetypes#48]
The tree of the android sdk folders has been slightly changed in the latest versions and also the Maven android plugin etc.When will you release a new release to fix these and other issues? 

Thanks!

**Comment by rciovati** [comment]
Hello,
I'm going to revamping a little bit these archetypes, you can see a preview in my fork:

https://github.com/rciovati/android-archetypes/tree/revamped

**Comment by ebiermann** [comment]
Hello Riccardo,

the changes look good. When you are finished with them, you can make a pull request and we will integrate them.

Regards,
Enrico

**Comment by jmdr** [comment]
That's sounds good.We hope to hear from you soon!

Thanks,

jmdr

**Comment by ebiermann** [comment]
Version 1.0.10 was released today and should be available via the archetype catalogue soon.

Regards,
Enrico
