### ISSUE TITLE
mvn release:prepare fails on fresh project created using the android-release archetype

### ISSUE THREAD

**Issue by matthewmichihara** [techatspree/android-archetypes#51]
Repro steps:
1. Create project using the android-release archetype: `mvn archetype:generate -DarchetypeArtifactId=android-release -DarchetypeGroupId=de.akquinet.android.archetypes -DarchetypeVersion=1.0.9 -DgroupId=com.testproject.android -DartifactId=testproject`.
2. Go to created directory: `cd testproject`.
2. Attempt to begin generating a signed release build: `mvn release:prepare`.

Result:
`➜ mvn release:prepare
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] testproject - Parent
[INFO] testproject - Application
[INFO] testproject-it - Integration tests
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building testproject - Parent 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-release-plugin:2.1:prepare (default-cli) @ testproject-parent ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] testproject - Parent .............................. FAILURE [0.434s]
[INFO] testproject - Application ......................... SKIPPED
[INFO] testproject-it - Integration tests ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.602s
[INFO] Finished at: Fri Apr 19 19:53:32 PDT 2013
[INFO] Final Memory: 8M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.1:prepare (default-cli) on project testproject-parent: Missing required setting: scm connection or developerConnection must be specified. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Comment by ebiermann** [comment]
Hello Matthew,

do you have specified the signing information for your apk? See https://github.com/akquinet/android-archetypes#the-android-release-archetype for instructions.

Please let us know if the problem persists.

Regards,
Enrico

**Comment by rciovati** [comment]
Hello,
In order to use the Maven Release plugin you need to add to the `pom.xml` the informations about your source control system and about the repository where to install the artifacts produced by the release phase.

In my `pom.xml` I have something like that:

``` xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <!--  All the other informations-->

    <distributionManagement>
        <repository>
            <id>local-repository</id>
            <url>file:///Users/rciovati/repo/</url>
        </repository>
    </distributionManagement>

    <scm>
        <url>https://bitbucket.org/rciovati/my-repo/src</url>
        <connection>scm:git:ssh://git@bitbucket.org/rciovati/my-repo.git</connection>
        <developerConnection>scm:git:ssh://git@bitbucket.org/rciovati/my-repo.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

</project>
```

If you need a different configuration (svn instead of git, remote repo instead of local,...) please refer to the documentation.

PS: Please use the `1.0.10` archetype version.

**Comment by matthewmichihara** [comment]
@ebiermann @rciovati Thanks for the help. It seems that I was missing the `scm` and `distributionManagement` information. Perhaps this info could be added to https://github.com/akquinet/android-archetypes#the-android-release-archetype or included in the initial `mvn archetype:generate` command since it is required to generate a release?

Is it possible for me to get this working without creating a local repository for the release APK? I just want to have an easy way to create a signed, proguarded, zipaligned apk.

Thanks!

**Comment by rciovati** [comment]
Try doing

mvn clean deploy -Pandroid-release,release

You will need to setup a local repo (it's just a directory) as well.

BR

Il giorno sabato 20 aprile 2013, Matthew Michihara ha scritto:

> @ebiermann https://github.com/ebiermann @rciovatihttps://github.com/rciovatiThanks for the help. It seems that I was missing the
> scm and distributionManagement information. Perhaps this info could be
> added to
> https://github.com/akquinet/android-archetypes#the-android-release-archetypeor included in the initial mvn
> archetype:generate command since it is required to generate a release?
> 
> Is it possible for me to get this working without creating a local
> repository for the release APK? I just want to have an easy way to create a
> signed, proguarded, zipaligned apk.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/akquinet/android-archetypes/issues/51#issuecomment-16706851
> .

## 

Riccardo Ciovati

**Comment by matthewmichihara** [comment]
Now I'm getting some kind of proguard related issue it seems when I run: `mvn clean deploy -Pandroid-release,release`

`[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] testproject2 - Parent
[INFO] testproject2 - Application
[INFO] testproject2-it - Integration tests
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building testproject2 - Parent 1.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ testproject2-parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ testproject2-parent ---
[INFO] Installing /Users/mmichihara/Code/pixeltreelabs/testproject2/pom.xml to /Users/mmichihara/.m2/repository/com/testproject2/android/testproject2-parent/1.3-SNAPSHOT/testproject2-parent-1.3-SNAPSHOT.pom
[INFO] 
[INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ testproject2-parent ---
Downloading: file:///Users/mmichihara/Desktop/com/testproject2/android/testproject2-parent/1.3-SNAPSHOT/maven-metadata.xml
Downloaded: file:///Users/mmichihara/Desktop/com/testproject2/android/testproject2-parent/1.3-SNAPSHOT/maven-metadata.xml (616 B at 85.9 KB/sec)
Uploading: file:///Users/mmichihara/Desktop/com/testproject2/android/testproject2-parent/1.3-SNAPSHOT/testproject2-parent-1.3-20130420.205933-3.pom
Uploaded: file:///Users/mmichihara/Desktop/com/testproject2/android/testproject2-parent/1.3-SNAPSHOT/testproject2-parent-1.3-20130420.205933-3.pom (4 KB at 1907.7 KB/sec)
Downloading: file:///Users/mmichihara/Desktop/com/testproject2/android/testproject2-parent/maven-metadata.xml
Downloaded: file:///Users/mmichihara/Desktop/com/testproject2/android/testproject2-parent/maven-metadata.xml (301 B at 147.0 KB/sec)
Uploading: file:///Users/mmichihara/Desktop/com/testproject2/android/testproject2-parent/1.3-SNAPSHOT/maven-metadata.xml
Uploaded: file:///Users/mmichihara/Desktop/com/testproject2/android/testproject2-parent/1.3-SNAPSHOT/maven-metadata.xml (616 B at 601.6 KB/sec)
Uploading: file:///Users/mmichihara/Desktop/com/testproject2/android/testproject2-parent/maven-metadata.xml
Uploaded: file:///Users/mmichihara/Desktop/com/testproject2/android/testproject2-parent/maven-metadata.xml (301 B)
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building testproject2 - Application 1.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ testproject2 ---
[INFO] Deleting /Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (default) @ testproject2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/src/templates/res
[INFO] 
[INFO] --- android-maven-plugin:3.5.3:generate-sources (default-generate-sources) @ testproject2 ---
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] ANDROID-904-002: Found aidl files: Count = 0
[INFO] Manifest merging disabled. Using project manifest only
[INFO] /Users/mmichihara/Code/sdks/android-sdk-macosx/platform-tools/aapt [package, -m, -J, /Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/generated-sources/r, -M, /Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/AndroidManifest.xml, -S, /Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/res, --auto-add-overlay, -A, /Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/assets, -I, /Users/mmichihara/Code/sdks/android-sdk-macosx/platforms/android-16/android.jar]
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ testproject2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/src/main/resources
[INFO] skip non existing resourceDirectory /Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/generated-sources/extracted-dependencies/src/main/resources
[INFO] 
[INFO] --- android-maven-plugin:3.5.3:manifest-update (manifestUpdate) @ testproject2 ---
[INFO] Attempting to update manifest /Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/AndroidManifest.xml
[INFO] Testing if node application is application
[INFO] Made changes to manifest file, updating /Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/AndroidManifest.xml
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ testproject2 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/classes
[INFO] 
[INFO] --- android-maven-plugin:3.5.3:proguard (default-proguard) @ testproject2 ---
[INFO] /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java [-Xmx512M, -jar, /Users/mmichihara/Code/sdks/android-sdk-macosx/tools/proguard/lib/proguard.jar, @proguard.cfg, -injars, '/Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/classes', -libraryjars, '/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/classes.jar', -libraryjars, '/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/jsse.jar', -libraryjars, '/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/jce.jar', -libraryjars, /Users/mmichihara/.m2/repository/com/google/android/android/4.1.1.4/android-4.1.1.4.jar(!org/xml/**,!org/w3c/**,!java/**,!javax/**), -libraryjars, '/Users/mmichihara/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar', -libraryjars, '/Users/mmichihara/.m2/repository/org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar', -libraryjars, '/Users/mmichihara/.m2/repository/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar', -libraryjars, '/Users/mmichihara/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar', -libraryjars, '/Users/mmichihara/.m2/repository/org/khronos/opengl-api/gl1.1-android-2.1_r1/opengl-api-gl1.1-android-2.1_r1.jar', -libraryjars, '/Users/mmichihara/.m2/repository/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.jar', -libraryjars, '/Users/mmichihara/.m2/repository/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar', -libraryjars, '/Users/mmichihara/.m2/repository/org/json/json/20080701/json-20080701.jar', -outjars, '/Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/proguard-obfuscated.jar', -dump, '/Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/proguard/dump.txt', -printseeds, '/Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/proguard/seeds.txt', -printusage, '/Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/proguard/usage.txt', -printmapping, '/Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/proguard/mapping.txt']
[INFO] Error: proguard.cfg (No such file or directory)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] testproject2 - Parent ............................. SUCCESS [0.286s]
[INFO] testproject2 - Application ........................ FAILURE [1.997s]
[INFO] testproject2-it - Integration tests ............... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.353s
[INFO] Finished at: Sat Apr 20 13:59:35 PDT 2013
[INFO] Final Memory: 15M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.3:proguard (default-proguard) on project testproject2: MojoExecutionException: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2 && /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java -Xmx512M -jar /Users/mmichihara/Code/sdks/android-sdk-macosx/tools/proguard/lib/proguard.jar @proguard.cfg -injars '/Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/classes' -libraryjars '/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/classes.jar' -libraryjars '/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/jsse.jar' -libraryjars '/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/../Classes/jce.jar' -libraryjars '/Users/mmichihara/.m2/repository/com/google/android/android/4.1.1.4/android-4.1.1.4.jar(!org/xml/**,!org/w3c/**,!java/**,!javax/**)' -libraryjars '/Users/mmichihara/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar' -libraryjars '/Users/mmichihara/.m2/repository/org/apache/httpcomponents/httpclient/4.0.1/httpclient-4.0.1.jar' -libraryjars '/Users/mmichihara/.m2/repository/org/apache/httpcomponents/httpcore/4.0.1/httpcore-4.0.1.jar' -libraryjars '/Users/mmichihara/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar' -libraryjars '/Users/mmichihara/.m2/repository/org/khronos/opengl-api/gl1.1-android-2.1_r1/opengl-api-gl1.1-android-2.1_r1.jar' -libraryjars '/Users/mmichihara/.m2/repository/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.jar' -libraryjars '/Users/mmichihara/.m2/repository/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar' -libraryjars '/Users/mmichihara/.m2/repository/org/json/json/20080701/json-20080701.jar' -outjars '/Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/proguard-obfuscated.jar' -dump '/Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/proguard/dump.txt' -printseeds '/Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/proguard/seeds.txt' -printusage '/Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/proguard/usage.txt' -printmapping '/Users/mmichihara/Code/pixeltreelabs/testproject2/testproject2/target/proguard/mapping.txt', Result = 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :testproject2`

**Comment by rciovati** [comment]
Thanks, you have found the first glitch :-)

You can fix it in two ways:

1) Adding `<config>proguard.conf</config>` in the `<proguard>`section of the `pom.xml`file
2) Renaming the proguard file: `mv proguard.conf proguard.cfg`
