### ISSUE TITLE
Wrong android-plugin version

### ISSUE THREAD

**Issue by wolpert** [techatspree/android-archetypes#58]
The wiki page says that 3.6.0 is used as the android-plugin version, but when I run the default build command, 3.5.3 is actually listed in the parent pom.xml file

Command: 
mvn archetype:generate \
  -DarchetypeArtifactId=android-release \
  -DarchetypeGroupId=de.akquinet.android.archetypes \
  -DarchetypeVersion=1.0.10 \
  -DgroupId=com.foo.bar \
  -DartifactId=my-android-project \
  -Dpackage=com.foo.bar.android \
  -Dversion=1.0-SNAPSHOT

grep android.plugin.version my-android-project/pom.xml 
                <android.plugin.version>3.5.3</android.plugin.version>

To find the correct aapt stuff for a standard 'mvn compile' required me to up this value to 3.6.0 due to a bug in 3.5.3 and r22.0.1

**Comment by rciovati** [comment]
You are right. 
The code to generate the 3.6.0 is already been pushed, an update should be release to fix this problem.

**Comment by rciovati** [comment]
@ebiermann it would be possible to issue a new release?

**Comment by ebiermann** [comment]
The new release is in progress and should be available soon.
