### ISSUE TITLE
Version should be snapshot

### ISSUE THREAD

**Issue by mosabua** [techatspree/android-archetypes#6]
The version of the created projects should be a -SNAPSHOT version so that the users do not trip into unexpected behaviour esp. when building in the module of the test project 

This would be confusing for Maven beginners and probably cause issues. Only a release should have a fixed version. In dev it should be SNAPSHOT..

**Comment by cescoffier** [comment]
Yes makes a lot of sense. Will fix it ASAP.

**Comment by mosabua** [comment]
wow... that was fast ;-)

**Comment by cescoffier** [comment]
Hi,

I've checked all archetypes, and the version is correctly set as a snapshot by default:

```
[INFO] Generating project in Interactive mode
[INFO] Using property: groupId = com.foo.bar
[INFO] Using property: artifactId = my-android-project
Define value for property 'version':  1.0-SNAPSHOT: : 
[INFO] Using property: package = com.foo.bar.android
[INFO] Using property: platform = 7
Confirm properties configuration:
groupId: com.foo.bar
artifactId: my-android-project
version: 1.0-SNAPSHOT
package: com.foo.bar.android
platform: 7
Y: : 
```

The CLI prompts the user to get the version but use 1.0-SNAPSHOT by default.

**Comment by mosabua** [comment]
Hm.... might be a problem with intellij then... I will investigate
