### ISSUE TITLE
Folder names

### ISSUE THREAD

**Issue by mosabua** [techatspree/android-archetypes#7]
Clemens, 

I am not sure if this will be possible, but here it is anyway. As you are probably aware it is a good practice to have a maven module folder name be the same as the artifactId, however the android artifacts just use hardcoded names like application and application-it ... ideally these folder and module names would match the artifactId of the two artifacts.. 

just my 2c

**Comment by cescoffier** [comment]
Hi,

Unfortunately this is not possible with archetypes... In fact, archetypes are quite limited. Maybe you know a magic trick to support such kind of stuff ?

**Comment by mosabua** [comment]
Are you sure? I was thinking of creating an issue with the archetype plugin but looking at this issue http://jira.codehaus.org/browse/ARCHETYPE-350 makes me think the folder name can already be parameterized..  might be worth experimenting a bit..

**Comment by mosabua** [comment]
Are you sure? I was thinking of creating an issue with the archetype plugin but looking at this issue http://jira.codehaus.org/browse/ARCHETYPE-350 makes me think the folder name can already be parameterized..  might be worth experimenting a bit..

**Comment by cescoffier** [comment]
Hi,

I was thinking to such kind of magic ! I will check if it works, and keep you posted.

**Comment by cescoffier** [comment]
Hi,

I've quickly tried, and unfortunately, it seems that the issue you gave me is unresolved.

**Comment by mosabua** [comment]
Yeah.. but it is hinting at having properties drive folder names.. I thought that could work but have not tried..

**Comment by manandbytes** [comment]
Is #16 a way that this issue may be resolved?

**Comment by cescoffier** [comment]
Hi, I think it fixed the issue. Once integrated we will close this issue and cut a new release.

**Comment by cescoffier** [comment]
It's fixed in the 1.0.6 version.

**Comment by mosabua** [comment]
Awesome!

**Comment by manandbytes** [comment]
You're welcome ;-)
