### ISSUE TITLE
Archetype-with-test error

### ISSUE THREAD

**Issue by tekblom** [techatspree/android-archetypes#8]
Hi,

I am kind of new to android-development with Maven and found these interesting archetypes. 

Archetype-getting-started worked really good but I get an error when creating the archetype-with-test in eclipse. It says "Can´t rename Can´t rename C:\ProcejtArea\MyTestApp". It creates some folders but I guess not all. I can´t either see it in the Package Explorer in Eclipse.

Do you know what the problem can bee?

Hope I am writing on the right place!

/Tobias

**Comment by cescoffier** [comment]
please be sure that the output folder does not exist.
did you also test the resulting project ?

Clement

**Comment by markus2610** [comment]
I had the error, too. Give in workspace location full path with project name and unchecked "Use default Workspace location". 

example:
in workspace location
{path user}\workspace\Android\testProject

Markus

**Comment by kentchiu** [comment]
I had this problem too.
It cause by parent folder name is same as application folder when importing  as eclipse project.
The archetype-with-test will create structure like this
myapp  (parent project)
- application (production project)
- application-it  (test project)
  When creating project, Eclipse will import project regarding to artifact name rather folder name, so 
  the artifact of  application (production project) is 'myapp' , it is conflict with parent project('myapp' in this case)
  so, my solution is rename the top level folder (parent project)  from 'myapp'   to 'myapp-all' , and re-import as maven project again, it works.
  After import, the projects in Eclipse workspace is like this:
  myapp-full
- application
- application-it
  myapp
  myapp-it

**Comment by cescoffier** [comment]
Can I close this issue ?
