### ISSUE TITLE
[android-with-test][eclipse] Missing artifacts, Missing master project

### ISSUE THREAD

**Issue by gvespucci** [techatspree/android-archetypes#9]
I just created a project using the android-with-test-archetype guide.

Importing in Eclipse Helios the following errors are raised:

<pre>
Missing artifact com.foo.bar:my-android-project:apk:1.0-SNAPSHOT:compile
Missing artifact com.foo.bar:my-android-project:jar:1.0-SNAPSHOT:compile
[WARN] The POM for com.foo.bar:my-android-project:apk:1.0-SNAPSHOT is missing, no dependency information available
[WARN] The POM for com.foo.bar:my-android-project:jar:1.0-SNAPSHOT is missing, no dependency information available
</pre>

The issue can be solved only invoking a 

<pre>$>mvn install</pre> 

on my-android-project, because the -it project references those artifacts in Maven dependencies.

Furthermore, in Java Browsing perspective, Projects tab, only the my-android-project-with-it is visible. Only in Project Explorer my-android-project (the master one) is visible, labelled as a simple Maven project, not a Maven Android one.
Should the master project be visible in Projects tab, too?

**Comment by cescoffier** [comment]
Hi,

Those issues are related to the m2eclipse maven bridge. Could you ask the question on maven-android-developers@googlegroups.com ?

Clement

**Comment by gvespucci** [comment]
Hi Clement
Could you kindly explain me why do you think so?

Giorgio

**Comment by cescoffier** [comment]
Hi,

It seems to not be Maven issues. The archetype just generates the projects, it does not deal with Eclipse integration. Eclipse integration is managed by m2eclipse and the android-m2eclipse integration bridge.

**Comment by gvespucci** [comment]
@cescoffier Thank you very much for the clarification and sorry for the delay :)
